#!/bin/bash

set -e

USAGE="
Obashidian - Obsidian Shell CLI (obsh)

Query data from obsidian vault for analysis and automation direct from the command line.

Usage:
${0} <cmd> <args>
"

obshcli="${0}"

# If is not in a vault, exit
if [[ ! -d ".obsidian" ]]; then
  echo "Error: This isn't an obsidian vault."
  exit 1
fi

CMD=${1?"${USAGE}"}
if [[ "${CMD}" == "tag" ]]; then
  shift
  TAG="#${1?"${USAGE}"}"

  # Grep all files in current dir but ignoring hidden files/dirs
  grep -r --exclude="*/\.*" "${TAG}" . | sed "s/${TAG}//" | sed -E "s/^\.\/(.*\.md):(.*)$/-\2 \n  \[ref](\1\) \n/"
  exit 0
fi

# In OSX, check if gdate is installed
if [[ "$(uname)" == "Darwin" ]]; then
  if [[ ! -x "$(command -v gdate)" ]]; then
    echo "Missing: For OSX 'gdate' is required for calculating dates."
    echo "Please install it with 'brew install coreutils'"
    exit 1
  fi
fi

## Helper function to calculate date in both OSX and Linux
function _date() {
  if [[ "$(uname)" == "Darwin" ]]; then
    gdate "${@}"
  else
    date "${@}"
  fi
}

yesterday="$(_date -d 'yesterday' +%d-%m-%Y)"
tomorrow="$(_date -d 'tomorrow' +%d-%m-%Y)"

# Reminder cmd
# Check if a reminder is due
# This is the reminder format #reminder:DD-MM-YYYY
if [[ "${CMD}" == "reminder" ]]; then
  shift
  DATE=${1-"$(date +%d-%m-%Y)"}
  echo "Reminders for ${DATE}"
  grep -r --exclude="*/\.*" "#reminder:${DATE}" . | sed -E "s/^\.\/(.*\.md):(.*)$/-\2 \n  \[ref](\1\) \n/"
  exit 0
fi

if [[ "${CMD}" == "reminders" ]]; then
  shift
  printf "All reminders \n\n"
  grep -r --exclude="*/\.*" "#reminder" . | sed -E "s/^\.\/(.*\.md):(.*)$/-\2 \n  \[ref](\1\) \n/"
  exit 0
fi

# Collect blocks of content from the vault
# This is the block format: 
#<!-- ini:<block_name> -->
#   content
#<!-- end:<block_name> -->
if [[ "${CMD}" == "block" ]]; then
  shift
  BLOCK=${1?"${USAGE}"}

  echo "-- ${BLOCK} --"
  grep -rl "<!-- ini:$BLOCK -->" . | \
    xargs -I{} awk "/<!-- ini:$BLOCK -->/{f=1;next} /<!-- end:$BLOCK -->/{f=0} f" {} 

  exit 0
fi

# Collects a sections of content from the vault
# A section starts with a ## title and goes till the next section
# This is the section format:
# ## SectionOne
#  content
# ## SectionTwo
if [[ "${CMD}" == "section" ]]; then
  shift
  SECTION=${1?"${USAGE}"}
  FILE=${2?"Requires a file to search for the section"}

  awk "/^## ${SECTION}/{f=1;next} /^##/{f=0} f" ${FILE}
  exit 0
fi

if [[ "${CMD}" == "daily" ]]; then
  shift
  echo "
---
title: Daily
date: $(_date +%d-%m-%Y)
---

[[daily/$yesterday|yesterday]]
[[daily/$tomorrow|tomorrow]]

## Todos

$($obshcli tag todo)

## Assumptions

$($obshcli tag assumption)

## Today reminders

$($obshcli reminder)

## Waiting

$($obshcli tag waiting)

## Inbox

$(obsh section Inbox daily/$yesterday.md)
"
  exit 0
fi
 
echo "ERROR: ${0} unknown command ${CMD}"
echo "${USAGE}"
exit 1
